site_name: TheNewEconomy Docs

repo_name: TheNewEconomy/EconomyCore
repo_url: https://github.com/TheNewEconomy/EconomyCore

nav:
  - Users:
    - TNE: 'index.md'
    - Setup: 'user/setup.md'
    - Currencies: 'user/currency.md'
  - Developers:
    - License: 'developer/license.md'
    - API: 'developer/api.md'
    - Implement Handler: 'developer/handlers.md'
    - Implement Platform: 'developer/platform.md'