site_name: TheNewMenuLibrary Docs

repo_name: TheNewEconomy/TNML
repo_url: https://github.com/TheNewEconomy/TNML

nav:
  - About: 'index.md'
  - Maven: 'maven.md'
  - Structure: 'structure.md'
  - Example: 'example.md'
  - Contributing: 'contribute.md'
  - License: 'license.md'